### ISSUE TITLE
Do not work when creating a new instance

### ISSUE THREAD

**Issue by diegodurante** [joeyAghion/opsworks_custom_env#25]
If we have already a running instance and we want to apply this cookbook we can follow this guide and then go inside AWS OpsWorks portal -> Stack -> Run command -> Update custom cookbooks.
In this way all is fine.

But if we want to create and launch a new instance this cookbook will not work because when we are trying to create the config/application.yml file the directory /srv/www/app_name/shared/config does not exist at this time (deploy event)!

So how can we improve this flow to make it works also for new instances?

I am working on a rails app. Maybe we can add something inside config/before_migrate.rb file?

**Comment by joeyAghion** [comment]
Hi @diegodurante. We start new instances frequently with this cookbook, but it turns out that we _also_ associate the recipe with our layer's **Setup** event (not just **Deploy**). I've updated the [README](https://github.com/joeyAghion/opsworks_custom_env) to mention this.

Let me know here if that doesn't work for you.

**Comment by diegodurante** [comment]
Hi @joeyAghion ,
are you sure that we need to add also to layer's **Setup** and not **Configure** event?

**Comment by joeyAghion** [comment]
Yes I am sure the recipe is only associated with the Setup and Deploy events.

Do you get the same error? This is strange, since the code that writes out the config/application.yml file is skipped if there's no shared/config directory:

https://github.com/joeyAghion/opsworks_custom_env/blob/4173b76c9741bc7358697f041711c6c73258ba25/definitions/custom_env_template.rb#L19

**Comment by diegodurante** [comment]
Hi @joeyAghion ,
yes adding the recipe also to layer's **Setup** event the new instance starts properly.
Sorry, was my mistake.

Thanks for your patience!
